######################################################################
# Automatically generated by qmake (2.01a) jeu. févr. 23 19:38:42 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lcan

# Input
HEADERS += FenPrincipale.h
SOURCES += FenPrincipale.cpp main.cpp
