#!/bin/bash

PRG_NAME="7Robot tcphub"
LOGFILE=/var/log/tcphub.log
PIDFILE=/var/run/tcphub.pid
PID=$(cat $PIDFILE 2> /dev/null)
CMD=tcphub

USECOLOR=yes
. /etc/rc.d/functions

case "$1" in
	start)
		stat_busy "Start $PRG_NAME"
		if [ -z "$PID" ]; then
			$CMD -p $PIDFILE -l $LOGFILE
			if [ $? -eq 0 ]; then
				stat_done
			else
				stat_fail
				exit 1
			fi
		else
			ps -p $PID > /dev/null
			if [ "$?" = "0" ]; then
				stat_fail
				exit 1
			else	
				$CMD -p $PIDFILE -l $LOGFILE
				if [ $? -eq 0 ]; then
					stat_done
				else
					stat_fail
					exit 1
				fi
			fi
		fi
		;;
	stop)
		stat_busy "Stopping $PRG_NAME"
		if [ -n "$PID" ]; then
			kill $PID &> /dev/null
			if [ $? -gt 0 ]; then
				stat_fail
				exit 1
			else
				rm $PIDFILE &> /dev/null
				stat_done
			fi
		else
			stat_fail
			exit 1
		fi
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
	;;
	*)
		echo "usage: $0 {start|stop|restart}"
esac
