######################################################################
# Automatically generated by qmake (2.01a) ven. févr. 24 16:59:49 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
LIBS += -lcan
# Input
HEADERS += FenAff.h
SOURCES += FenAff.cpp main.cpp
