######################################################################
# Automatically generated by qmake (2.01a) ven. févr. 24 09:30:37 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FenAff.h
SOURCES += FenAff.cpp main.cpp
